// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpgiybwiztpqbskuvdka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwZ2l5YndpenRwcWJza3V2ZGthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NTc5MDIsImV4cCI6MjA2MTUzMzkwMn0.i4J-6ZdZb8RpRhYdb5mK8xbFd1Z3cndvPe8i-v_i0Y0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);